### ISSUE TITLE
Exercise 5.6: No discount appearing in equation

### ISSUE THREAD

**Issue by Jonathan2021** [vojtamolda/reinforcement-learning-an-introduction#1]
In your equation for Q(s,a) using Weighted Importance Sampling, you separated Rt from what happens in subsequent timesteps but didn't discount Gt+1 by lambda.

**A**) Also, can't we just keep the original V(s) expression with t in T(s, a) (instead of t in T(s)), the importance sampling ratio starting from t+1 to T-1 on both sides of the division (for timestep t probability of selecting a is 1 because it already happened) and keeping Gt.

**B**) It is true that if t = T-1 then the ratio from t+1 to T-1 is ill defined but that was already the case in the original expression.

Thanks for reading !

PS: Your corrections are by far the best, most complete and correct ones I have found. Keep up the good work ;)

**Comment by vojtamolda** [comment]
Thanks for reporting the mistake and for the kind words, @Jonathan2021. I'm still reading the book, now in chapter 12, so more is coming 😃

I'm on vacation now but I'll make a reminder, take a look at it and fix it once I'm back.

**Comment by vojtamolda** [comment]
Thanks for the correction. You're right. The discount factor is indeed missing from the equation. I'm just submitting a patch to fix it.

Now regarding your additional points:

**A**) I think the summation *t in T(s, a)* wouldn't be correct. The definition of *Q(s, a)* only conditions the first action to be *a*. The future visits to *s* don't have this conditioning but the summation over *T(s, a)* would incorrectly enforce it for all subsequent visits. It would effectively ignore contributions from taking all the other actions different than *a* from *s*. 

There's another way to see it isn't correct. The entire formula can be rewritten with the use of the original equation for *V(s)* (5.6) like this: 

<img width="150" alt="IMG_0562" src="https://user-images.githubusercontent.com/8467740/127235307-882ccd40-3140-461c-9ac5-70fb2af1eae2.PNG">.

Where *s_t* is the state right after *s*. Summation over *T(s, a)* is a slightly different but not identical value and wouldn't allow this transformation.

**B**) Text of the book mentions handling of this corner case but it's easy to miss. The importance ratio is equal to 0 if the denominator is 0. I adopted the assumption but didn't explicitly mention it.

PS: Thanks for warm the comment. I'm actually very surprised that people are reading my hand written scribbles :)

**Comment by Jonathan2021** [comment]
Hey @vojtamolda,
Didn't have much time to dig into this before now sorry.
- I get that my expression with **A)** would be false but not for the same reasons. By distributing the ratio in `G = Rt+1 + gamma Gt+1` (thus obtaining `ratio * Rt+1 + ratio * gamma * Gt+1`), I would get your expression (from the correction) but with `Rt+1` multiplied by the ratio and divided by the sum (which you probably don't want because the terms in the ratio would only be about stuff that comes afterwards).

- On the other hand I don't really get your point about enforcing all subsequent visits to s to take action `a` (I probably just didn't understand what you were trying to say). If `T(s,a)` is the first-visit to s followed by action `a`, then another visit to `s` in the episode followed by any action doesn't change anything to the expression.
I think your expression in the correction is incorrect.
![241192030_4855874681109128_7509079177242194868_n](https://user-images.githubusercontent.com/44318644/131984127-28f59adc-9433-4660-9488-cb4ceb7bbb41.jpg)
`T(s)` being, by definition, all timesteps where s was first visited, the `t` in the red section would be the first time `s` was visited in an episode no matter the following action. `t` could be before the first visit to `(s, a)` if `s` was visited before without taking action `a`. This will sum returns and ratios we don't want to estimate `Q(s,a)`.
And even if you replace `s` by `s'` (`s'` being the state that occured after taking action `a` in `s` in the first visit), `s'` could have occured before too as it is not necessarily visited only by taking action `a` prior.


I hope all by blabbering makes some sense.
