### ISSUE TITLE
Error to Exercise 2.4

### ISSUE THREAD

**Issue by earthwuyang** [vojtamolda/reinforcement-learning-an-introduction#10]
Hello @vojtamolda , when I calculate the formula in Exercise 2.4 I found it should be j=i+1. But I'm not sure if I'm right. Could you have a look when you have free time? Thanks.
![微信图片_20220213153520](https://user-images.githubusercontent.com/53375253/154013151-ca675fc3-66a8-4dea-8cba-c114c615f537.jpg)

**Comment by vojtamolda** [comment]
Hi again!

Yeah. I checked it and I think you're right here as well. The summation should start from `j = i + 1`. Also, there's a little bit of an "unwritten convention" in there. When the blue summation bound starts from `n+1` and goes to `n` the product should be equal to 1, so it correctly recovers the term `$\alpha_n R_n$` that you wrote separately. I tried to include it in the blue summation but it isn't very elegant...

The correct solution looks like this, I think:

<img width="692" alt="Correction" src="https://user-images.githubusercontent.com/8467740/154103711-2cfa47b8-b5ba-4328-bc1f-a85dd512e0ff.png">
