### ISSUE TITLE
[Exercise 2.2] Question about solution (possible error)

### ISSUE THREAD

**Issue by ShawnHymel** [vojtamolda/reinforcement-learning-an-introduction#13]
Thank you for posting these solutions! I have a question about your solution for exercise 2.2. After computing the rewards for t=4, we have the Q values: [-1, +1/3, 0, 0]. As a result, action 2 (A2) should be the optimal action (at Q= +1/3). However, the agent chose A3 going into t=5, which is not optimal. Does that mean both A<sub>4</sub> and A<sub>5</sub> should both be considered definite &#949; cases (rather than just A<sub>4</sub>)?

<img width="1053" alt="Screen Shot 2022-05-18 at 12 56 44 PM" src="https://user-images.githubusercontent.com/5232145/169146119-9f77b080-4df5-4243-ad39-ea00dfe2a7ac.png">

**Comment by vojtamolda** [comment]
I'm not sure if I understand your question. I don't think A<sub>5</sub> exists in this exercise.

The way my notation works is that A<sub>1</sub> uses values from Q<sub>0</sub> (initial state equal to all zeros) and the received reward updates the estimate to Q<sub>1</sub>. So A<sub>5</sub> would take you from Q<sub>5</sub> to Q<sub>6</sub>, but this transition is never mentioned in the text of the exercise.

**Comment by ShawnHymel** [comment]
Hi @vojtamolda,

Thank you for the quick response! I didn't quite follow the labeling, so let me see if I can describe it better. I'm still new to reinforcement learning, and I'm still learning the terminology.

From Q<sub>3</sub> to Q<sub>4</sub> (which I think you refer to as A<sub>4</sub>), the agent selects action 2 (with average expected reward of -1/2). Because it did not select action 3 or 4 (each with average expected reward of 0), we can say that A<sub>4</sub> was the ε case (exploratory). 

From Q<sub>4</sub> to Q<sub>5</sub> (A<sub>5</sub>), the average expected rewards (before going into t=5) are given by Q<sup>4</sup> = [-1 +1/3 0 0]. The agent selects action 3, which has an average expected reward of 0. Why did it not select action 2, which had the highest expected reward? Is that because this choice was also an ε case? Or is there some other reason it chose action 3?

**Comment by vojtamolda** [comment]
Sorry @ShawnHymel, I don't really have bandwidth to explain content of the book here. The material is pretty dense, so I usually ended up re-reading a chapter a few times until it all clicked.

I think the solution to this exercise is correct. In fact, I recently fixed it in #9. But if there's still an error, feel free to reopen the issue and get back to me.

Thanks!

**Comment by gilzamir18** [comment]
I think that is wrong yet, because is right in step 5 is exploration. Note that A1  is based on Q1 table and A5 is based on Q5 table, where Q1 = [0, 0, 0, 0].
![image](https://user-images.githubusercontent.com/54516662/187450573-5fe8f282-9abd-4fee-8618-fa8b926eb076.png)
