### ISSUE TITLE
Exercise 2.2: A5 is also a random action

### ISSUE THREAD

**Issue by duxtinto** [vojtamolda/reinforcement-learning-an-introduction#20]
Hi @vojtamolda !

Thank you very much for this repo...your explanations for the exercises are really good, and they are really helping me to understand the concepts of the book.

I think that there is an error on the exercise 2.2... 

![image](https://github.com/vojtamolda/reinforcement-learning-an-introduction/assets/333268/dd941fb6-db74-4f67-93a5-fdec32da6435)

as you indicated on the Q4 table, the greedy action is 2, but on t=5 the selected action was 3, and unless I'm missing something, that means that A5 was also definitely random.
Is this right?

Thank you very much.

**Comment by vojtamolda** [comment]
Hello @duxtinto,

Thanks a lot for opening the issue. I think you're right. I'll submit a fix in a few minutes. The 3-rd action should be green underlined in $Q_4$. Since the 3-rd action isn't the highest expected value, the action must have been taken by random.

Cheers,

  Vojta

**Comment by duxtinto** [comment]
> Hello @duxtinto,
> 
> Thanks a lot for opening the issue. I think you're right. I'll submit a fix in a few minutes. The 3-rd action should be green underlined in Q4. Since the 3-rd action isn't the highest expected value, the action must have been taken by random.
> 
> Cheers,
> 
> Vojta

Cool! 

Thank you very much.
