### ISSUE TITLE
Question. Chapter 5, exercise 5.12: reversed return sequence

### ISSUE THREAD

**Issue by boldyshev** [vojtamolda/reinforcement-learning-an-introduction#3]
del

**Comment by vojtamolda** [comment]
Hello @boldyshev! Thanks for closing the issue and the kind words. I quickly checked the code and I agree that it calculates the returns correctly.

I also don't think there's any discounting needed in the `np.cumsum(...)` call. You're right that all the rewards are -1 for this specific exercise. I tried to write the solutions generally without specially optimizing them for the exercises. Theoretically the method should work on any `gym.Env` with the same action and state space. The reward values are of course arbitrary in the general case.

**Comment by boldyshev** [comment]
> You're right that all the rewards are -1 for this specific exercise. I tried to write the solutions generally without specially optimizing them for the exercises. Theoretically the method should work on any gym.Env with the same action and state space. The reward values are of course arbitrary in the general case.

Oh, I see. Sorry for bothering.
