### ISSUE TITLE
Exercise 5.6: No averaging and uncoherent times.

### ISSUE THREAD

**Issue by Jonathan2021** [vojtamolda/reinforcement-learning-an-introduction#4]
Hey @vojtamolda,
I commented all the following content on the issue you closed on the same exercise.
I am not familiar with GitHub issues and figured I would reference it in a new issue in case you didn't receive a notification.

I didn't have much time to dig into your answer before now sorry.

- I don't really get your point about enforcing all subsequent visits to s to take action `a` (I probably just didn't understand what you were trying to say). If `T(s,a)` is the first-visit to s followed by action `a`, then another visit to `s` in the episode followed by any action doesn't change anything to the expression.
I think your expression in the correction is incorrect.
![241192030_4855874681109128_7509079177242194868_n](https://user-images.githubusercontent.com/44318644/131984127-28f59adc-9433-4660-9488-cb4ceb7bbb41.jpg)
`T(s)` being, by definition, all timesteps where s was first visited, the `t` in the red section would be the first time `s` was visited in an episode no matter the following action. `t` could be before the first visit to `(s, a)` if `s` was visited before without taking action `a`. This will sum returns and ratios we don't want to estimate `Q(s,a)`.
And even if you replace `s` by `s'` (`s'` being the state that occured after taking action `a` in `s` in the first visit), `s'` could have occured before too as it is not necessarily visited only by taking action `a` prior.

- Another reason why your expression is incorrect is the following (even with my proposed modifications above). Suppose you only have episodes that end after the first occurence of `(s, a)` (meaning we only get one reward). In this case, `Gt+1 = 0` and `Gt=Rt+1` all the time. Now your expression can be reduced to `sum of all Rt+1`, which is incorrect because it isn't averaged in any way.

By replacing `T(s)` by `T(s,a)` in the original expression (first-visit times where `s` was followed by action `a`) and adding new notation to the importance sampling ratio (to avoid corner cases), I get the following.
![241430179_544679293508327_1163890976622465113_n](https://user-images.githubusercontent.com/44318644/132240082-4fd820ff-9e05-407f-9aa2-61edb1d5d5bd.jpg)
**Edit**: Error when defining the new ratio expression above. It is `ρ(a)t:t` = 1 and not `ρ(a)t:t+1 = 1`.

It's true that Rt+1 is scalled by stuff that comes afterwards but this is the case for every individual reward in `G`. The paragraph on ***Dicounting-aware importance sampling*** deals with this.

I hope all by blabbering makes some sense.

_Originally posted by @Jonathan2021 in https://github.com/vojtamolda/reinforcement-learning-an-introduction/issues/1#issuecomment-912410855_

**Comment by vojtamolda** [comment]
Hello @Jonathan2021,

Thanks for opening the issue. I’ll eventually get to it. It’s very time consuming to get the right context in my head to be able to understand the whole thing.

In the meantime, have tried looking for a solution written by somebody else? Just to have another independent view?

**Comment by Jonathan2021** [comment]
No worries I am in no hurry.
I can't seem to find any expression of the state-action value estimate using monte carlo importance sampling built from scratch anywhere. This is all I found.

- [Solution of the exercise from another repo](https://github.com/LyWangPX/Reinforcement-Learning-2nd-Edition-by-Sutton-Exercise-Solutions/blob/master/Chapter%205/Solutions_to_Reinforcement_Learning_by_Sutton_Chapter_5_r3.pdf)

- At the bottom of [this post](https://lazyprogrammer.me/monte-carlo-with-importance-sampling-for-reinforcement-learning/), they have a similar expression as mine.

Also, by looking into the algorithm used to estimate `Q(s,a)` you can derive the formula (page 110 in the book).

**Comment by vojtamolda** [comment]
@Jonathan2021, thanks for opening the issue and explaining the problem. I finally found big enough time window to work on this issue. I believe you're right. My solution is wrong.

I was able to retrace my thinking steps and I arrived at the wrong answer by doing a simple (and pretty stupid) algebraic error. I cancelled the sample averaging sums without realizing how they actually work.

**Comment by Jonathan2021** [comment]
@vojtamolda , no problem :wink: Thanks for taking the time to dig into this. These errors happen to the best of us !
