### ISSUE TITLE
Exercise 3.22

### ISSUE THREAD

**Issue by hhoppe** [vojtamolda/reinforcement-learning-an-introduction#7]
Within the summations, should the factor be $\gamma^{2k}$ because there are two steps to cycle around the loop of two states?

**Comment by vojtamolda** [comment]
Hi! Thanks a lot for submitting the issue. I think you're right. The term in brackets is for the whole cycle, i.e. from the decision point back to the decision point, so `k`, a step index, should jump by two. It takes two steps to complete the whole cycle.

Here's a corrected solution. Please @hhoppe, let me know if you got the same result. The correct result looks (luckily) very similar.
<img width="814" alt="Result" src="https://user-images.githubusercontent.com/8467740/153250806-1f009a00-179f-458d-afdf-7636952c346d.png">

And here's how I worked out the sum of only the even terms in a geometric series. I hope I haven't embarassed myself by making a silly mistake somewhere...
<img src="https://user-images.githubusercontent.com/8467740/153250831-7cc2c2d8-73fe-4006-8a3c-75cb138ac472.jpg" width=450>

**Comment by hhoppe** [comment]
Yes, that matches what I get; thanks so much!

**Comment by vojtamolda** [comment]
Fixed!
